SET ECHO ON;

STARTUP;

CREATE OR REPLACE DIRECTORY &1 AS '&2';

DROP USER qateam CASCADE;

CREATE USER qateam IDENTIFIED BY qateam;

DROP USER crapply CASCADE;

CREATE USER crapply IDENTIFIED BY crapply;

DROP USER csteam CASCADE;

CREATE USER csteam IDENTIFIED BY csteam;

DROP USER mon_ttc CASCADE;

CREATE USER mon_ttc IDENTIFIED BY mon_ttc;

DROP USER itropicsteam CASCADE;

CREATE USER itropicsteam IDENTIFIED BY itropicsteam;

DROP USER itropics_c CASCADE;

CREATE USER itropics_c IDENTIFIED BY itropics_c;

DROP USER prodn CASCADE;

CREATE USER prodn IDENTIFIED BY prodn;

DROP USER erpteam CASCADE;

CREATE USER erpteam IDENTIFIED BY erpteam;

DROP USER smsreports CASCADE;

CREATE USER smsreports IDENTIFIED BY smsreports;

DROP USER custom_ttc CASCADE;

DROP TABLESPACE CUSTOM_TAB_DLYONLN INCLUDING CONTENTS;

CREATE TABLESPACE CUSTOM_TAB_DLYONLN 
   DATAFILE '/apps/oradata/&3/custom_tbs.dbf' SIZE 100M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE 1024M;

DROP USER cs_ttc CASCADE;

DROP TABLESPACE CS_TAB_DLYONLN INCLUDING CONTENTS;

CREATE TABLESPACE CS_TAB_DLYONLN 
   DATAFILE '/apps/oradata/&3/cs_tbs.dbf' SIZE 50M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE 1024M;

DROP USER sc_ttc CASCADE;

DROP TABLESPACE SC_TAB_DLYONLN INCLUDING CONTENTS;

CREATE TABLESPACE SC_TAB_DLYONLN 
   DATAFILE '/apps/oradata/&3/sc_tbs.dbf' SIZE 50M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE 1024M;

DROP USER pr_ttc CASCADE;

DROP TABLESPACE PR_TAB_DLYONLN INCLUDING CONTENTS;

CREATE TABLESPACE PR_TAB_DLYONLN 
   DATAFILE '/apps/oradata/&3/pr_tbs.dbf' SIZE 50M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE 1024M;

DROP USER rs_ttc CASCADE;

DROP TABLESPACE RS_TAB_DLYONLN INCLUDING CONTENTS;

CREATE TABLESPACE RS_TAB_DLYONLN 
   DATAFILE '/apps/oradata/&3/rs_tbs.dbf' SIZE 50M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE 1024M;

DROP USER op_ttc CASCADE;

DROP TABLESPACE OP_TAB_DLYONLN INCLUDING CONTENTS;

CREATE TABLESPACE OP_TAB_DLYONLN 
   DATAFILE '/apps/oradata/&3/op_tbs.dbf' SIZE 50M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE 1024M;

DROP USER prodn CASCADE;

DROP TABLESPACE PRODN_TAB INCLUDING CONTENTS;

CREATE TABLESPACE PRODN_TAB 
   DATAFILE '/apps/oradata/&3/prodn_tbs.dbf' SIZE 50M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE 1024M;

DROP USER itropics CASCADE;

DECLARE
   CURSOR synonym_cur
   IS
      SELECT a.synonym_name
        FROM dba_synonyms a
       WHERE     a.owner = 'PUBLIC'
             AND a.table_owner IN
                    ('CS_TTC',
                     'RS_TTC',
                     'OP_TTC',
                     'PR_TTC',
                     'SC_TTC',
                     'CUSTOM_TTC');

   v_drop_sql   VARCHAR2 (50);
BEGIN
   FOR syn IN synonym_cur
   LOOP
      v_drop_sql := 'DROP PUBLIC SYNONYM ' || syn.synonym_name;

      EXECUTE IMMEDIATE v_drop_sql;
   END LOOP;
END;
/

EXIT;